# Generated by Django 4.2.3 on 2023-07-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastros_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
